src/Entity/Trade.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TradeRepository")
 */
class Trade
{
    const UNPAY = 0; //未付款
    const PAIED = 1;  //已付款
    const CLOSE = 2;  //已关闭

    const UNSEND = 0;
    const SENDING = 1;
    const RECIVER = 2;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tradeNo;


    /**
     * @ORM\Column(type="float")
     */
    private $totalAmount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $examineTime;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $givePoints;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Member", inversedBy="trades")
     */
    private $member;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\GoodsSnapshot", mappedBy="trade", cascade={"persist", "remove"})
     */
    private $goodsSnapshot;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PayLog", inversedBy="trade", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $payLog;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createTime;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logisticsStatus;

    public function __construct()
    {
        $this->goodsSnapshot = new ArrayCollection();
        mt_srand((double) microtime() * 1000000);
        $this->tradeNo = "DD".date('Ymd') . str_pad(mt_rand(1, 99999), 5, '0', STR_PAD_LEFT);
        $this->status = self::UNPAY;
        $this->logisticsStatus = self::UNSEND;
        $dateTime = new \DateTime('now');
        $this->setCreateTime($dateTime);
        $dateTime->modify("+30 minute");
        $this->setExamineTime($dateTime);
    }

    public function getWePayInfo()
    {
        return array(
            'out_trade_no' => time(),
            'total_fee' => $this->totalAmount * 100, // 订单金额**单位：分**
            'body' => '支付'.$this->tradeNo,
            'openid' => 'onkVf1FjWS5SBIixxxxxxx',
            'attach' => 'goods',
        );
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTradeNo(): ?string
    {
        return $this->tradeNo;
    }

    public function setTradeNo(string $tradeNo): self
    {
        $this->tradeNo = $tradeNo;

        return $this;
    }




    public function getTotalAmount(): ?float
    {
        return $this->totalAmount;
    }

    public function setTotalAmount(float $totalAmount): self
    {
        $this->totalAmount = $totalAmount;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getExamineTime(): ?\DateTimeInterface
    {
        return $this->examineTime;
    }

    public function setExamineTime(?\DateTimeInterface $examineTime): self
    {
        $this->examineTime = $examineTime;

        return $this;
    }

    public function getGivePoints(): ?float
    {
        return $this->givePoints;
    }

    public function setGivePoints(?float $givePoints): self
    {
        $this->givePoints = $givePoints;

        return $this;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(?Member $member): self
    {
        $this->member = $member;

        return $this;
    }

    /**
     * @return Collection|GoodsSnapshot[]
     */
    public function getGoodsSnapshot(): Collection
    {
        return $this->goodsSnapshot;
    }

    public function addGoodsSnapshot(GoodsSnapshot $goodsSnapshot): self
    {
        if (!$this->goodsSnapshot->contains($goodsSnapshot)) {
            $this->goodsSnapshot[] = $goodsSnapshot;
            $goodsSnapshot->setTrade($this);
        }

        return $this;
    }

    public function removeGoodsSnapshot(GoodsSnapshot $goodsSnapshot): self
    {
        if ($this->goodsSnapshot->contains($goodsSnapshot)) {
            $this->goodsSnapshot->removeElement($goodsSnapshot);
            // set the owning side to null (unless already changed)
            if ($goodsSnapshot->getTrade() === $this) {
                $goodsSnapshot->setTrade(null);
            }
        }

        return $this;
    }

    public function getPayLog(): ?PayLog
    {
        return $this->payLog;
    }

    public function setPayLog(PayLog $payLog): self
    {
        $this->payLog = $payLog;

        return $this;
    }

    public function getFirstImage()
    {
        $goods = $this->getGoodsSnapshot()->first();
        assert($goods instanceof GoodsSnapshot);
        return $goods->getGoodsImg();
    }

    public function getCreateTime(): ?\DateTimeInterface
    {
        return $this->createTime;
    }

    public function setCreateTime(\DateTimeInterface $createTime): self
    {
        $this->createTime = $createTime;

        return $this;
    }

    public function getLogisticsStatus(): ?string
    {
        return $this->logisticsStatus;
    }

    public function setLogisticsStatus(?string $logisticsStatus): self
    {
        $this->logisticsStatus = $logisticsStatus;

        return $this;
    }
}

src/Controller/MemberController.php
<?php
/**
 * Created by PhpStorm.
 * User: 烽行天下
 * Date: 2019/2/27
 * Time: 23:32
 * Site: http://www.drupai.com
 */

namespace App\Controller;


use App\Entity\Address;
use App\Entity\Cash;
use App\Entity\Exchange;
use App\Entity\Member;
use App\Entity\PointsLog;
use App\Entity\User;
use App\Entity\WeChat;
use App\Entity\WechatConfig;
use App\Form\AddressForm;
use App\Form\CashForm;
use App\Form\ExchangeForm;
use App\Servers\WeChatServer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator;
use Yansongda\Pay\Pay;

/**
 * Class MemberController
 * @package App\Controller
 * @Route("/member")
 * @IsGranted("ROLE_USER")
 */

class MemberController extends AbstractController
{


    /**
     * @Route("/", name="member_center")
     * 用户中心主页
     */
    public function index()
    {
        return $this->render("member/index.html.twig");
    }

    /**
     * @Route("/salelink", name="member_sale_link")
     * 推荐页面
     */
    public function saleLink(WeChatServer $wechatServer)
    {
        $wechat = $this->getUser();
        $image = $wechatServer->createQrcode($wechat);

        return $this->render("member/recommend.html.twig",['image'=>$image]);
    }

    /**
     * @Route("/exchange", name="member_exchange")
     * 充值页面
     */
    public function exchange(Request $request)
    {
        $form = $this->createForm(ExchangeForm::class,new Exchange());
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $data = $form->getData();

            $config = $this->getWechatPayConfig();
            $info = $data->getPayInfo();
            $info['openid'] = $this->getWechat()->getOpenid();
            $info['notify_url'] = $this->generateUrl("wx_respond",[], UrlGeneratorInterface::ABSOLUTE_URL);
            dump($config);exit;
            $em = $this->getDoctrine()->getManager();
            $em->persist($data);
            $em->flush();
            $pay = Pay::wechat($config)->mp($info);

            return $this->redirectToRoute('member_center');
        }

        return $this->render("member/exchange.html.twig",[
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/cash", name="member_cash")
     * 提现页面
     */
    public function cash(Request $request)
    {
        $cash = new Cash();
        $member = $this->getMember();
        $form = $this->createForm(CashForm::class,$cash);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $cash = $form->getData();
            $member->addCashLog($cash);
            $amount = $cash->getAmount();
            if($amount > $member->getAmount()){
                $this->addFlash('error',"余额不足，请重新输入");
            }
            $member->addAmount('-'.$amount);
            $amountLog = new PointsLog();
            $amountLog->setChangeReason('提现到微信')
                ->setAmount('-'.$amount)
                ->setLogType(PointsLog::CASH);
            $member->addPointsLog($amountLog);
            $em = $this->getDoctrine()->getManager();
            $em->persist($member);
            $em->flush();
        }
        return $this->render("member/cash.html.twig",['form' => $form->createView()]);
    }

    /**
     * @Route("/sale/center", name="sale_center")
     * 销售中心
     */
    public function saleCenter()
    {
        return $this->render("member/salecenter.html.twig");
    }

    /**
     * @Route("/edit", name="member_edit")
     * 编辑用户信息
     */
    public function edit()
    {
        return $this->render("member/edit.html.twig");
    }

    /**
     * @Route("/order/list", name="order_list")
     * 订单列表
     */
    public function orderList()
    {
        return $this->render("member/order_list.html.twig");
    }

    /**
     * @Route("/address/list", name="address_list")
     * 收货地址
     */
    public function addressList()
    {
        $addreses = $this->getMember()->getAddress();
        return $this->render("member/address_list.html.twig",['addresses' => $addreses]);
    }

    /**
     * @Route("/address/add", name="address_add")
     * 添加收货地址
     */
    public function addAddress(Request $request)
    {
        $member = $this->getMember();
        $address = new Address();
        $form = $this->createForm(AddressForm::class,$address);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $address = $form->getData();
            $member->addAddress($address);
            $em = $this->getDoctrine()->getManager();
            $em->persist($member);
            $em->flush();
            return $this->redirectToRoute("address_list");
        }

        return $this->render('member/address_add.html.twig',[
            'form'=>$form->createView(),
            'member' => $member
        ]);
    }

    /**
     * @Route("/reply/list", name="reply_list")
     * 会员留言列表
     */
    public function replyList()
    {
        $replies = $this->getMember()->getReplies();
        return $this->render("member/reply_list.html.twig",['replies'=>$replies]);
    }

    /**
     * @Route("/assess/list", name="assess_list")
     * 会员评论列表
     */
    public function assessList()
    {
        $assesses = $this->getMember()->getAssess();
        return $this->render("member/assess_list.html.twig",['assesses'=>$assesses]);
    }

    /**
     * @Route("/rank/list", name="rank_list")
     * 会员积分排行列表
     */
    public function rankList()
    {
        return $this->render("member/ranking_list.html.twig");
    }

    public function getWechat(): ? WeChat
    {
        return $this->getUser();
    }

    public function getWUser(): ?User
    {
        return $this->getWechat()->getUser();
    }

    public function getMember(): ?Member
    {
        return $this->getWUser()->getMember();
    }

    public function getWechatPayConfig()
    {
        $em = $this->getDoctrine()->getManager();
        $wechatConfig = $em->getRepository(WechatConfig::class)->find(1);
        return $wechatConfig->getPayConfig();
    }



}

templates/member/address_add.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <header class="bar bar-nav">
        <a href="{{ path("address_list") }}" class="icon icon-left pull-left"></a>
        <h1 class="title">添加地址</h1>
    </header>
{% endblock %}

{% block body %}
    <div class="list-block">
        {{ form_start(form) }}
        <ul>
            <li>
                <div class="item-content">
                    <div class="item-media"><i class="icon icon-form-name"></i></div>
                    <div class="item-inner">
                        <div class="item-title label">{{ form_label(form.fullAddress) }}</div>
                        <div class="item-input">
                            {{ form_widget(form.fullAddress,{'id': 'city-picker'}) }}
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="item-content">
                    <div class="item-media"><i class="icon icon-form-password"></i></div>
                    <div class="item-inner">
                        <div class="item-title label">{{ form_label(form.zipCode) }}</div>
                        <div class="item-input">
                            {{ form_widget(form.zipCode) }}
                        </div>
                    </div>
                </div>
            </li>
            <!-- Date -->
            <li>
                <div class="item-content">
                    <div class="item-media"><i class="icon icon-form-calendar"></i></div>
                    <div class="item-inner">
                        <div class="item-title label">{{ form_label(form.addressee) }}</div>
                        <div class="item-input">
                            {{ form_widget(form.addressee,{'value': member.realName}) }}
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="item-content">
                    <div class="item-media"><i class="icon icon-form-calendar"></i></div>
                    <div class="item-inner">
                        <div class="item-title label">{{ form_label(form.phone) }}</div>
                        <div class="item-input">
                            {{ form_widget(form.phone,{'value': member.phone}) }}
                        </div>
                    </div>
                </div>
            </li>
            <input type="hidden" name="_csrf_token"
                   value="{{ csrf_token('_token') }}"
            >
        </ul>
        <div class="content-block">
            <div class="row">
                <div class="col-50"><a href="{{ path("member_center") }}" class="button button-big button-fill button-danger">返回</a></div>
                <div class="col-50"><button type="submit" class="button button-big button-fill button-success">提交</button></div>
            </div>
        </div>
{{ form_end(form) }}
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="//g.alicdn.com/msui/sm/0.6.2/js/sm-city-picker.min.js" charset="utf-8"></script>
    <script>
        $("#city-picker").cityPicker({
            toolbarTemplate: '<header class="bar bar-nav">\
            <button class="button button-link pull-right close-picker">确定</button>\
               <h1 class="title">选择收货地址</h1>\
             </header>'
        });
    </script>
{% endblock %}

templates/member/address_list.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <header class="bar bar-nav">
        <a href="{{ path("member_center") }}" class="icon icon-left pull-left"></a>
        <h1 class="title">我的地址</h1>
    </header>
{% endblock %}


{% block body %}
    <div class="content">
        <div class="list-block media-list">
            <ul>
                {% for address in addresses %}
                <li>
                    <a href="#" class="item-link item-content">
                        <div class="item-inner">
                            <div class="item-title-row">
                                <div class="item-title">收件人：</div>
                                <div class="item-after">{{ address.addressee }}</div>
                            </div>
                            <div class="item-subtitle">电话：{{ address.phone }}</div>
                            <div class="item-text">{{ address.fullAddress }}</div>
                        </div>
                    </a>
                </li>
                {% endfor %}
                <li>
                    <a href="{{ path('address_add') }}" class="item-link item-content">
                        <div class="item-inner">
                            <div class="item-title-row">
                                <div class="item-title">添加地址</div>
                            </div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>

    </div>
{% endblock %}

templates/member/amount_log.html.twig
<div class="content-padded">
    <div class="row">
        <div class="col-33">时间</div>
        <div class="col-33">备注</div>
        <div class="col-33">金额</div>
    </div>
    {% for log in amountLog %}
        {% if log.logType == 1 or log.logType == 2 %}
            <div class="row">
                <div class="col-33">{{ log.changeTime | date('Y-m-d H:i:s') }}</div>
                <div class="col-33">{{ log.changeReason }}</div>
                <div class="col-33">{{ log.amount }}</div>
            </div>
        {% endif %}
    {% endfor %}
</div>

templates/member/cash.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <header class="bar bar-nav">
        <a href="{{ path("sale_center") }}" class="icon icon-left pull-left"></a>
        <h1 class="title">提现中心</h1>
    </header>
{% endblock %}

{% block body %}
    <div class="content">
        {{ form_start(form) }}
        {{ form_label(form.amount) }}
        {{ form_widget(form.amount) }}
        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >
        <button class="btn btn-lg btn-primary" type="submit">
            马上提现
        </button>
        {{ form_end(form) }}

    </div>
{% endblock %}

templates/member/edit.html.twig
{% extends 'base.html.twig' %}

{% set member = app.user.user %}
{% set wechat = app.user %}

{% block header %}
    <header class="bar bar-nav">
        <a href="{{ path("member_center") }}" class="icon icon-left pull-left"></a>
        <h1 class="title">我的信息</h1>
    </header>
{% endblock %}

{% block body %}
    <div class="content">
        <div class="list-block">
            <ul>
                <!-- Text inputs -->
                <li>
                    <div class="item-content">
                        <div class="item-media"><i class="icon icon-form-name"></i></div>
                        <div class="item-inner">
                            <div class="item-title label">用户名</div>
                            <div class="item-input">
                                <input type="text" placeholder="{{ member.username }}">
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="item-content">
                        <div class="item-media"><i class="icon icon-form-password"></i></div>
                        <div class="item-inner">
                            <div class="item-title label">密码</div>
                            <div class="item-input">
                                <input type="password" placeholder="******" class="">
                            </div>
                        </div>
                    </div>
                </li>
                <!-- Date -->
                <li>
                    <div class="item-content">
                        <div class="item-media"><i class="icon icon-form-calendar"></i></div>
                        <div class="item-inner">
                            <div class="item-title label">生日</div>
                            <div class="item-input">
                                <input type="date" placeholder="Birth day" value="2014-04-30">
                            </div>
                        </div>
                    </div>
                </li>
                <input type="hidden" name="_csrf_token"
                       value="{{ csrf_token('_token') }}"
                >
            </ul>

            <div class="content-block">
                <div class="row">
                    <div class="col-50"><a href="{{ path("member_center") }}" class="button button-big button-fill button-danger">返回</a></div>
                    <div class="col-50"><a href="#" class="button button-big button-fill button-success">提交</a></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/member/exchange.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <header class="bar bar-nav">
        <h1 class="title">充值中心</h1>
    </header>
{% endblock %}

{% block body %}
    <div class="content">
        {{ form_start(form) }}
        <label for="amount" class="sr-only">Openid</label>
            {{ form_row(form.amount) }}
        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >
        <button class="btn btn-lg btn-primary" type="submit">
            确认充值
        </button>
            {{ form_end(form) }}

    </div>
{% endblock %}

templates/member/index.html.twig
{% extends 'base.html.twig' %}

{% set user = app.user.user %}
{% set wechat = app.user %}
{% set member = user.member %}
{% block header %}
    <header class="bar bar-nav">
        <a href="{{ path("home_page") }}" class="icon icon-left pull-left"></a>
        <h1 class="title">会员中心</h1>
    </header>
{% endblock %}

{% block body %}
    <div class="content">
        <div class="card member-card-header-pic">
            <div class="card-content">
                <div class="card-content-inner member-inner">
                    <div class="list-block media-list">
                        <ul>
                            <li class="item-content">
                                <div class="item-media">
                                    <img src="{{ wechat.headImg }}" width="72" class="headImg">
                                </div>
                                <div class="item-inner">
                                    <div class="item-subtitle color-while">会员ID: {{ user.username }}</div>
                                    <div class="item-subtitle">微信昵称: {{ wechat.nickname }}</div>
                                    <div class="item-subtitle">关注时间: {{ wechat.subscribeTime|date("Y-m-d") }}</div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="buttons-tab member-tabs">
                    <a href="#tab1" class="tab-link button"><span class="fa fa-clipboard-list"></span>订单</a>
                    <a href="#tab2" class="tab-link button"><span class="fa fa-coins"></span>积分</a>
                    <a href="#tab3" class="tab-link button"><span class="fa fa-money-check-alt"></span>余额</a>
                    <a href="#tab4" class="tab-link button"><span class="fa fa-gift"></span>红包</a>
                </div>
            </div>
        </div>
        <div class="member-content">
            <div class="tabs">

                <div class="account content-inner tab active" id="tab-index">
                    <div class="list-block">
                        <ul>
                            <li>
                                <a href="{{ path("sale_center")}}"  class="item-link item-content"  >
                                    <div class="item-inner">
                                        <div class="item-title">分销中心</div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="{{ path("member_edit",{ 'id' : app.user.id}) }}" class="item-link item-content">
                                    <div class="item-inner">
                                        <div class="item-title">用户信息</div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="{{ path("order_list") }}" class="item-link item-content">
                                    <div class="item-inner">
                                        <div class="item-title">我的订单</div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="{{ path("address_list") }}" class="item-link item-content">
                                    <div class="item-inner">
                                        <div class="item-title">收货地址</div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="{{ path("reply_list") }}" class="item-link item-content">
                                    <div class="item-inner">
                                        <div class="item-title">我的留言</div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="{{ path("assess_list") }}" class="item-link item-content">
                                    <div class="item-inner">
                                        <div class="item-title">我的评论</div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="{{ path("logout") }}" class="item-link item-content">
                                    <div class="item-inner">
                                        <div class="item-title">退出登录</div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div id="tab1" class="tab">
                    <div class="content-block">
                        {{ include('member/order_item.html.twig',{'orders': member.trades}) }}
                        <a href="#tab-index"  class="tab-link item-content"  >
                            <div class="item-inner">
                                <div class="item-title">返回会员中心</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div id="tab2" class="tab">
                    <div class="content-block">
                        {{ include('member/points_log.html.twig',{'pointsLog': member.pointsLog}) }}
                        <a href="#tab-index"  class="tab-link item-link item-content"  >
                            <div class="item-inner">
                                <div class="item-title">返回会员中心</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div id="tab3" class="tab">
                    <div class="content-block">
                        {{ include('member/amount_log.html.twig',{'amountLog': member.pointsLog}) }}
                        <a href="#tab-index"  class="tab-link item-link item-content"  >
                            <div class="item-inner">
                                <div class="item-title">返回会员中心</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div id="tab4" class="tab">
                    <div class="content-block">
                        <p>您还没有红包</p>
                        <a href="#tab-index"  class="tab-link item-link item-content"  >
                            <div class="item-inner">
                                <div class="item-title">返回会员中心</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/member/order_item.html.twig
{% for order in orders %}
<div class="list-block media-list order-item-{{ order.tradeNo }}">
    <ul>
        <li>
            <a  href="{{ path('show_order',{'id': order.id}) }}" class="item-link item-content" >
                {% if  order.firstImage != null %}
                <div class="item-media"><img src="{{ absolute_url(asset(order.firstImage)) }}" width="80"></div>
                {% endif %}

                    <div class="item-inner">
                        <div class="item-title-row">
                            <div class="item-title">订单编号{{ order.tradeNo }}</div>

                        </div>
                        <div class="pull-right">{{ order.totalAmount }}元</div>
                        <div class="item-subtitle">订单状态：{{ order.status == 1 ? '已付款':'未付款' }}</div>
                        <div class="item-text">下单时间: {{ order.createTime | date('Y-m-d H:i:s') }}</div>
                    </div>
                </a>
            {% if order.status == 0 %}
                <span class="order-item-after icon icon-remove" data-no="{{ order.tradeNo }}"></span>
            {% endif %}
        </li>
    </ul>
</div>
        {% else %}

            <div class="list-block media-list">
            <ul>
                <li>
                    <a href="#" class="item-link item-content">
                        <div class="item-inner">
                            <div class="item-title-row">
                                <div class="item-title">还没有订单</div>
                            </div>
                        </div>
                    </a>
                </li>
            </ul>
            </div>
{% endfor %}

templates/member/order_list.html.twig
{% extends 'base.html.twig' %}
{% set user = app.user.user %}
{% set wechat = app.user %}
{% set member = user.member %}
{% block header %}
    <header class="bar bar-nav">
        <a href="#" class="icon icon-left pull-left back"></a>
        <h1 class="title">我的订单</h1>
    </header>
{% endblock %}

{% block body %}
    <div class="content">
        {{ include('member/order_item.html.twig',{'orders': member.trades}) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(".icon-remove").click(function(event){
            var dist = $(this);
            var parent = dist.parent().parent().parent();
            $.confirm("您确认要删除该订单?",function(){
                var no = dist.data('no');
                $.post('/order/del',{'no': no},function(res){
                    $.alert(res.msg);
                    if(res.status == 200){
                        parent.remove();
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/member/recommend.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    <header class="bar bar-nav">
        <h1 class="title">分享中心</h1>
    </header>
{% endblock %}
{% block body %}
    <div class="content">
        <img src="{{ image }}" width="100%" />
    </div>
{% endblock %}